In [1]:
import numpy as np

In [3]:
input = [[1,2,3, 2.5],
         [2.0,5.0,-1.0, 2.0],
            [-1.5,2.7,3.3, -0.8]]
weights=[[0.2,0.8,-0.5,1.0],
            [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

layer1_outputs=np.dot(input, np.array(weights).T) + biases

print(layer1_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [5]:
weights2 =[[0.2,0.8,-0.5],
            [0.5,-0.91,0.26],
            [-0.26,-0.27,0.17]]

biases2=[2,3,0.5]

layer2_outputs=np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)


[[ 2.7355   4.919   -0.66925]
 [ 2.232    9.1491  -1.2913 ]
 [ 3.1098   2.75535 -0.14595]]
